### ISSUE TITLE
MILIGHT status

### ISSUE THREAD

**Issue by WesRos** [athombv/com.milight#19]
Milight version: 3.1.7 (it was already in earlier versions, eg. last stable).

When turn a milight on in Effect Modus. The status tag stays in status OFF instead of ON.
So the light is ON, but Homey thinks it's OFF.

Even the trigger: "When Light is Switch On" didn't react when Homey turn the MILIGHT ON with an effect.

**Comment by RobinBol** [comment]
Thanks for reporting this issue! I'll put it on my to do list to fix.

**Comment by RobinBol** [comment]
Hi @WesRos are you sure this issue is still occurring on Milight app version 3.1.8? I have checked the code and a while back I fixed this exact issue. At least if I understand your scenario properly: you turn on the milight bulb via the flow card 'enable effect mode', and expect the status of the bulb in the mobile card to be 'on'?

Could you let me know if this issue still exists? Else I will close this issue.

**Comment by WesRos** [comment]
Yes, it Works. Thanks

**Comment by RobinBol** [comment]
Great, thanks for reporting!
