### ISSUE TITLE
Wrong colors miLight RGB+White (red == blue)

### ISSUE THREAD

**Issue by eelco2k** [athombv/com.milight#21]
I'm having trouble setting colors of my MiLight RGBW led strip in combination with  miLight wifi controller.

Also changing the settings with "Change red and green values to" and "Color tint calibration" makes no difference.

example:

I set "blue" on Homey color wheel -> color LEDs becomes "red"
I set "green" on Homey color wheel -> color leds becomes "green"
I put "red" on Homey color wheel -> color leds becomes "blue".

Connection is correct because with the included Wi-Fi remote control of MiLight and also through the iphone app, setting of the color of the leds are OK.

**Comment by RobinBol** [comment]
What milight app version are you on?

Since milights have different colors all over there is no way for homey to know the correct settings. You need to play a bit with the color calibration and perhaps even de change red/green values. For my RGBW led strip I have change red/green off, and a calibration value of 0.35. Does that help?

**Comment by eelco2k** [comment]
i'm on version 3.1.8. 
It does work when i check "red/green" = "on" with calibration value of "0.35". 

Thnx!
